# Generated by Django 5.1.1 on 2024-10-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_article_pub_date_message'),
    ]

    operations = [
    ]
