# Generated by Django 5.1.1 on 2024-10-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_restaurant_alter_member_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.product'),
        ),
        migrations.AddField(
            model_name='member',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='myapp.restaurant'),
        ),
    ]
