# Generated by Django 5.1.1 on 2024-10-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_member_favorite_products_member_favorite_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='quoted_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='myapp.message'),
        ),
    ]
