# Generated by Django 5.1.1 on 2024-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
